### ISSUE TITLE
ERROR: polymer init app-drawer-template

### ISSUE THREAD

**Issue by oneezy** [Polymer/polymer-cli#167]
Having a problem with **"polymer init app-drawer-template"**

![image](https://cloud.githubusercontent.com/assets/7369575/15383707/ba4eddc8-1d5a-11e6-9a4e-1570cd199aa2.png)

        Oneeezy@Oneezy MINGW64 ~/Desktop/new app
        $ polymer init app-drawer-template
        info:    Running template app-drawer-template
        info:    Downloading latest release of Polymer/app-drawer-template
        error:   Could not download release from Polymer/app-drawer-template
        error:   Uncaught exception: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

        Oneeezy@Oneezy MINGW64 ~/Desktop/new app
        $

**Comment by oneezy** [comment]
This is odd.. But to my knowledge nothing _major_  has been done differently..I ran the command again and now I'm getting this error: 



        Oneeezy@Oneezy MINGW64 ~/Desktop/app
        $ polymer init app-drawer-template
        info:    Running template app-drawer-template
        info:    Downloading latest release of Polymer/app-drawer-template


        I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.


        bower                           ENOENT No bower.json present




![image](https://cloud.githubusercontent.com/assets/7369575/15385494/9c7a28fe-1d67-11e6-844a-20f51fb7efc9.png)

**Comment by moderndeveloperllc** [comment]
I'm getting the same error when trying to init the `shop` template.

**Comment by CaptainCodeman** [comment]
It doesn't appear to create the bower file - try running init with the elements option first as a workaround

**Comment by justinfagnani** [comment]
The correct answer to this conundrum, is that it's I/O time, and to have a little patience :)

**Comment by moderndeveloperllc** [comment]
@justinfagnani I'm not sure I follow. The command is exiting out before any data is being downloaded from Github. I'm not cancelling it in the middle of the command or anything, and this is not a background task correct?

**Comment by justinfagnani** [comment]
The templates aren't available yet

**Comment by justinfagnani** [comment]
I'm not sure why it appeared to succeed the second try. That's probably bad.

**Comment by justinfagnani** [comment]
Oh... the template is live. Looking into it.

**Comment by FredKSchott** [comment]
We've tracked down the bug to our github request logic. See https://github.com/Polymer/polymer-cli/pull/169

**Comment by FredKSchott** [comment]
This fix has been pushed to npm within v0.8.0 https://www.npmjs.com/package/polymer-cli

**Comment by robrez** [comment]
Also getting errors on windows 7 via gitbash..

```
$ polymer --version
0.8.0
```

```
$ polymer init app-drawer-template
[32minfo[39m:    Running template app-drawer-template
[32minfo[39m:    Downloading latest release of Polymer/app-drawer-template
[32minfo[39m:    Unpacking template files
[32minfo[39m:    Finished writing template files

I'm all done. Running bower install for yourself to install the required dependencies. If this fails, try running the command yourself.

bower ENOENT  No bower.json present
```

Side note: Because strict workplace firewall stuff, I use https:// instead of svn://

**Comment by benjamincobb** [comment]
This bug still exists in Windows 10. I have polymer-cli version 0.8.0. The output is the same as oneezy's.

**Comment by justinfagnani** [comment]
@benjamincobb unfortunately, I think the Windows issue is slightly different and Windows specific. We're spending the next few days stabilizing Windows with new CI servers and local VMs for development. Sorry about the turbulence!

**Comment by benjamincobb** [comment]
@justinfagnani alright, thank you for the response! Good luck!

**Comment by summers173** [comment]
Same error here on windows 10, polymer --version 0.11.1, nont the shop or app-drawer-templates works

**Comment by summers173** [comment]
By the moment you can: 

git clone https://github.com/Polymer/app-drawer-template.git

**Comment by ThePeach** [comment]
Just tried to follow the [build your app tutorial](https://www.polymer-project.org/1.0/start/toolbox/set-up) and I got the same error:

    $ polymer init app-drawer-template
    info:    Running template polymer-init-app-drawer-template:app...
    error:   Template polymer-init-app-drawer-template:app not found
    error:   cli runtime exception: Error: Template polymer-init-app-drawer-template:app not found
    error:   Error: Template polymer-init-app-drawer-template:app not found
    at /home/peach/.nvm/versions/node/v5.12.0/lib/node_modules/polymer-cli/lib/init/init.js:164:19

initialising the `shop` template lead to no errors.

**Comment by web-padawan** [comment]
@ThePeach `app-drawer-template` was moved. Try `polymer init starter-kit` instead.

**Comment by ThePeach** [comment]
good point and thanks for opening #1783 !
