### ISSUE TITLE
errors and warnings from `polymer build`

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer-cli#219]
I have attempted to use the polymer-cli to start an `application: A blank application template`. The init process works, but `polymer build` produces several warnings and errors :

```
[sc-toolbox]$ which polymer
/home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/polymer
[sc-toolbox]$ ls -l $(which polymer)
lrwxrwxrwx 1 davidmaxwaterman davidmaxwaterman 46 May 27 11:51 /home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/polymer -> ../lib/node_modules/polymer-cli/bin/polymer.js
[sc-toolbox]$ ls -i /home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/../lib/node_modules/polymer-cli/bin/polymer.js
11885941 /home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/../lib/node_modules/polymer-cli/bin/polymer.js
[sc-toolbox]$ ls -i ~/z/polymer-cli/bin/polymer.js 
11885941 /home/davidmaxwaterman/z/polymer-cli/bin/polymer.js
[sc-toolbox]$ (cd ~/z/polymer-cli/ && git log | head)
commit 1e4a6841be3b9f1d48be918074c6516dc959adf4
Author: Fred K. Schott <fschott@google.com>
Date:   Thu May 26 15:37:31 2016 -0700

    0.10.0

commit c510b1140318319ac5d3cfef6b49b9da28b371fd
Merge: 7635a5b bf6556d
Author: Justin Fagnani <justin@fagnani.com>
Date:   Thu May 26 14:51:27 2016 -0700
[sc-toolbox]$ ls
[sc-toolbox]$ polymer init
? Which starter template would you like to use? application
info:    Running template application
? Application name Scientific Calculator
? Main element name o1-webapps-scientific-calculator
? Brief description of the application A Scientific Calculator.
   create bower.json
   create index.html
   create manifest.json
   create README.md
   create src/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator.html
   create test/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator_test.html

Project generated!
Installing dependencies...


I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.


bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower iron-demo-helpers#^1.0.0  cached git://github.com/PolymerElements/iron-demo-helpers.git#1.2.3
bower iron-demo-helpers#^1.0.0         validate 1.2.3 against git://github.com/PolymerElements/iron-demo-helpers.git#^1.0.0
bower iron-component-page#^1.0.0         cached git://github.com/PolymerElements/iron-component-page.git#1.1.6
bower iron-component-page#^1.0.0       validate 1.1.6 against git://github.com/PolymerElements/iron-component-page.git#^1.0.0
bower webcomponentsjs#^0.7.0             cached git://github.com/webcomponents/webcomponentsjs.git#0.7.22
bower webcomponentsjs#^0.7.0           validate 0.7.22 against git://github.com/webcomponents/webcomponentsjs.git#^0.7.0
bower polymer#^1.4.0                     cached git://github.com/Polymer/polymer.git#1.4.0
bower polymer#^1.4.0                   validate 1.4.0 against git://github.com/Polymer/polymer.git#^1.4.0
bower web-component-tester#^4.0.0        cached https://github.com/Polymer/web-component-tester.git#4.2.2
bower web-component-tester#^4.0.0      validate 4.2.2 against https://github.com/Polymer/web-component-tester.git#^4.0.0
bower paper-styles#^1.0.0                cached git://github.com/PolymerElements/paper-styles.git#1.1.4
bower paper-styles#^1.0.0              validate 1.1.4 against git://github.com/PolymerElements/paper-styles.git#^1.0.0
bower iron-icons#^1.0.0                  cached git://github.com/PolymerElements/iron-icons.git#1.1.3
bower iron-icons#^1.0.0                validate 1.1.3 against git://github.com/PolymerElements/iron-icons.git#^1.0.0
bower marked-element#^1.0.0              cached git://github.com/polymerelements/marked-element.git#1.1.3
bower marked-element#^1.0.0            validate 1.1.3 against git://github.com/polymerelements/marked-element.git#^1.0.0
bower paper-icon-button#^1.0.0           cached git://github.com/PolymerElements/paper-icon-button.git#1.1.1
bower paper-icon-button#^1.0.0         validate 1.1.1 against git://github.com/PolymerElements/paper-icon-button.git#^1.0.0
bower iron-location#^0.8.0               cached git://github.com/PolymerElements/iron-location.git#0.8.3
bower iron-location#^0.8.0             validate 0.8.3 against git://github.com/PolymerElements/iron-location.git#^0.8.0
bower prism-element#^1.0.0               cached git://github.com/PolymerElements/prism-element.git#1.0.4
bower prism-element#^1.0.0             validate 1.0.4 against git://github.com/PolymerElements/prism-element.git#^1.0.0
bower iron-flex-layout#^1.0.0            cached git://github.com/PolymerElements/iron-flex-layout.git#1.3.1
bower iron-flex-layout#^1.0.0          validate 1.3.1 against git://github.com/PolymerElements/iron-flex-layout.git#^1.0.0
bower hydrolysis#^1.18                   cached git://github.com/Polymer/hydrolysis.git#1.24.0
bower hydrolysis#^1.18                 validate 1.24.0 against git://github.com/Polymer/hydrolysis.git#^1.18
bower iron-doc-viewer#^1.0.1             cached git://github.com/PolymerElements/iron-doc-viewer.git#1.0.14
bower iron-doc-viewer#^1.0.1           validate 1.0.14 against git://github.com/PolymerElements/iron-doc-viewer.git#^1.0.1
bower iron-ajax#^1.0.0                   cached git://github.com/PolymerElements/iron-ajax.git#1.2.0
bower iron-ajax#^1.0.0                 validate 1.2.0 against git://github.com/PolymerElements/iron-ajax.git#^1.0.0
bower iron-selector#^1.0.0               cached git://github.com/PolymerElements/iron-selector.git#1.5.2
bower iron-selector#^1.0.0             validate 1.5.2 against git://github.com/PolymerElements/iron-selector.git#^1.0.0
bower paper-header-panel#^1.0.0          cached git://github.com/PolymerElements/paper-header-panel.git#1.1.6
bower paper-header-panel#^1.0.0        validate 1.1.6 against git://github.com/PolymerElements/paper-header-panel.git#^1.0.0
bower paper-toolbar#^1.0.0               cached git://github.com/PolymerElements/paper-toolbar.git#1.1.4
bower paper-toolbar#^1.0.0             validate 1.1.4 against git://github.com/PolymerElements/paper-toolbar.git#^1.0.0
bower font-roboto#^1.0.1                 cached git://github.com/PolymerElements/font-roboto.git#1.0.1
bower font-roboto#^1.0.1               validate 1.0.1 against git://github.com/PolymerElements/font-roboto.git#^1.0.1
bower iron-icon#^1.0.0                   cached git://github.com/polymerelements/iron-icon.git#1.0.8
bower iron-icon#^1.0.0                 validate 1.0.8 against git://github.com/polymerelements/iron-icon.git#^1.0.0
bower iron-iconset-svg#^1.0.0            cached git://github.com/polymerelements/iron-iconset-svg.git#1.0.9
bower iron-iconset-svg#^1.0.0          validate 1.0.9 against git://github.com/polymerelements/iron-iconset-svg.git#^1.0.0
bower marked#~0.3.3                      cached https://github.com/chjj/marked.git#0.3.5
bower marked#~0.3.3                    validate 0.3.5 against https://github.com/chjj/marked.git#~0.3.3
bower paper-behaviors#^1.0.0             cached git://github.com/PolymerElements/paper-behaviors.git#1.0.11
bower paper-behaviors#^1.0.0           validate 1.0.11 against git://github.com/PolymerElements/paper-behaviors.git#^1.0.0
bower test-fixture#^1.0.0                cached git://github.com/polymerelements/test-fixture.git#1.1.1
bower test-fixture#^1.0.0              validate 1.1.1 against git://github.com/polymerelements/test-fixture.git#^1.0.0
bower prism#*                            cached https://github.com/LeaVerou/prism.git#1.5.0
bower prism#*                          validate 1.5.0 against https://github.com/LeaVerou/prism.git#*
bower lodash#^3.7.0                      cached https://github.com/lodash/lodash.git#3.10.1
bower lodash#^3.7.0                    validate 3.10.1 against https://github.com/lodash/lodash.git#^3.7.0
bower accessibility-developer-tools#^2.10.0           cached https://github.com/GoogleChrome/accessibility-developer-tools.git#2.10.0
bower accessibility-developer-tools#^2.10.0         validate 2.10.0 against https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0
bower mocha#^2.3.0                                    cached https://github.com/mochajs/mocha.git#2.5.3
bower mocha#^2.3.0                                  validate 2.5.3 against https://github.com/mochajs/mocha.git#^2.3.0
bower sinon-chai#^2.7.0                               cached https://github.com/domenic/sinon-chai.git#2.8.0
bower sinon-chai#^2.7.0                             validate 2.8.0 against https://github.com/domenic/sinon-chai.git#^2.7.0
bower stacky#^1.3.0                                   cached https://github.com/PolymerLabs/stacky.git#1.3.2
bower stacky#^1.3.0                                 validate 1.3.2 against https://github.com/PolymerLabs/stacky.git#^1.3.0
bower sinonjs#^1.14.1                                 cached https://github.com/blittle/sinon.js.git#1.17.1
bower sinonjs#^1.14.1                               validate 1.17.1 against https://github.com/blittle/sinon.js.git#^1.14.1
bower chai#^3.2.0                                     cached https://github.com/chaijs/chai.git#3.5.0
bower chai#^3.2.0                                   validate 3.5.0 against https://github.com/chaijs/chai.git#^3.2.0
bower async#^1.5.0                                    cached https://github.com/caolan/async.git#1.5.2
bower async#^1.5.0                                  validate 1.5.2 against https://github.com/caolan/async.git#^1.5.0
bower paper-button#^1.0.0                             cached git://github.com/PolymerElements/paper-button.git#1.0.12
bower paper-button#^1.0.0                           validate 1.0.12 against git://github.com/PolymerElements/paper-button.git#^1.0.0
bower promise-polyfill#^1.0.0                         cached git://github.com/polymerlabs/promise-polyfill.git#1.0.0
bower promise-polyfill#^1.0.0                       validate 1.0.0 against git://github.com/polymerlabs/promise-polyfill.git#^1.0.0
bower iron-meta#^1.0.0                                cached git://github.com/polymerelements/iron-meta.git#1.1.1
bower iron-meta#^1.0.0                              validate 1.1.1 against git://github.com/polymerelements/iron-meta.git#^1.0.0
bower iron-checked-element-behavior#^1.0.0            cached git://github.com/PolymerElements/iron-checked-element-behavior.git#1.0.4
bower iron-checked-element-behavior#^1.0.0          validate 1.0.4 against git://github.com/PolymerElements/iron-checked-element-behavior.git#^1.0.0
bower iron-behaviors#^1.0.0                           cached git://github.com/PolymerElements/iron-behaviors.git#1.0.16
bower iron-behaviors#^1.0.0                         validate 1.0.16 against git://github.com/PolymerElements/iron-behaviors.git#^1.0.0
bower paper-ripple#^1.0.0                             cached git://github.com/PolymerElements/paper-ripple.git#1.0.5
bower paper-ripple#^1.0.0                           validate 1.0.5 against git://github.com/PolymerElements/paper-ripple.git#^1.0.0
bower paper-material#^1.0.0                           cached git://github.com/PolymerElements/paper-material.git#1.0.6
bower paper-material#^1.0.0                         validate 1.0.6 against git://github.com/PolymerElements/paper-material.git#^1.0.0
bower iron-validatable-behavior#^1.0.0                cached git://github.com/PolymerElements/iron-validatable-behavior.git#1.1.1
bower iron-validatable-behavior#^1.0.0              validate 1.1.1 against git://github.com/PolymerElements/iron-validatable-behavior.git#^1.0.0
bower iron-form-element-behavior#^1.0.0               cached git://github.com/PolymerElements/iron-form-element-behavior.git#1.0.6
bower iron-form-element-behavior#^1.0.0             validate 1.0.6 against git://github.com/PolymerElements/iron-form-element-behavior.git#^1.0.0
bower iron-a11y-keys-behavior#^1.0.0                  cached git://github.com/PolymerElements/iron-a11y-keys-behavior.git#1.1.2
bower iron-a11y-keys-behavior#^1.0.0                validate 1.1.2 against git://github.com/PolymerElements/iron-a11y-keys-behavior.git#^1.0.0
bower iron-demo-helpers#^1.0.0                       install iron-demo-helpers#1.2.3
bower iron-component-page#^1.0.0                     install iron-component-page#1.1.6
bower webcomponentsjs#^0.7.0                         install webcomponentsjs#0.7.22
bower paper-styles#^1.0.0                            install paper-styles#1.1.4
bower iron-icons#^1.0.0                              install iron-icons#1.1.3
bower polymer#^1.4.0                                 install polymer#1.4.0
bower marked-element#^1.0.0                          install marked-element#1.1.3
bower paper-icon-button#^1.0.0                       install paper-icon-button#1.1.1
bower prism-element#^1.0.0                           install prism-element#1.0.4
bower web-component-tester#^4.0.0                    install web-component-tester#4.2.2
bower iron-location#^0.8.0                           install iron-location#0.8.3
bower iron-flex-layout#^1.0.0                        install iron-flex-layout#1.3.1
bower iron-doc-viewer#^1.0.1                         install iron-doc-viewer#1.0.14
bower iron-selector#^1.0.0                           install iron-selector#1.5.2
bower paper-header-panel#^1.0.0                      install paper-header-panel#1.1.6
bower hydrolysis#^1.18                               install hydrolysis#1.24.0
bower iron-ajax#^1.0.0                               install iron-ajax#1.2.0
bower paper-toolbar#^1.0.0                           install paper-toolbar#1.1.4
bower font-roboto#^1.0.1                             install font-roboto#1.0.1
bower iron-icon#^1.0.0                               install iron-icon#1.0.8
bower iron-iconset-svg#^1.0.0                        install iron-iconset-svg#1.0.9
bower paper-behaviors#^1.0.0                         install paper-behaviors#1.0.11
bower test-fixture#^1.0.0                            install test-fixture#1.1.1
bower marked#~0.3.3                                  install marked#0.3.5
bower prism#*                                        install prism#1.5.0
bower accessibility-developer-tools#^2.10.0          install accessibility-developer-tools#2.10.0
bower lodash#^3.7.0                                  install lodash#3.10.1
bower mocha#^2.3.0                                   install mocha#2.5.3
bower sinon-chai#^2.7.0                              install sinon-chai#2.8.0
bower stacky#^1.3.0                                  install stacky#1.3.2
bower sinonjs#^1.14.1                                install sinonjs#1.17.1
bower paper-button#^1.0.0                            install paper-button#1.0.12
bower promise-polyfill#^1.0.0                        install promise-polyfill#1.0.0
bower iron-checked-element-behavior#^1.0.0           install iron-checked-element-behavior#1.0.4
bower iron-meta#^1.0.0                               install iron-meta#1.1.1
bower chai#^3.2.0                                    install chai#3.5.0
bower iron-behaviors#^1.0.0                          install iron-behaviors#1.0.16
bower paper-material#^1.0.0                          install paper-material#1.0.6
bower paper-ripple#^1.0.0                            install paper-ripple#1.0.5
bower async#^1.5.0                                   install async#1.5.2
bower iron-validatable-behavior#^1.0.0               install iron-validatable-behavior#1.1.1
bower iron-form-element-behavior#^1.0.0              install iron-form-element-behavior#1.0.6
bower iron-a11y-keys-behavior#^1.0.0                 install iron-a11y-keys-behavior#1.1.2

iron-demo-helpers#1.2.3 bower_components/iron-demo-helpers
├── iron-flex-layout#1.3.1
├── iron-icons#1.1.3
├── iron-location#0.8.3
├── marked-element#1.1.3
├── paper-icon-button#1.1.1
├── paper-styles#1.1.4
├── polymer#1.4.0
└── prism-element#1.0.4

iron-component-page#1.1.6 bower_components/iron-component-page
├── hydrolysis#1.24.0
├── iron-ajax#1.2.0
├── iron-doc-viewer#1.0.14
├── iron-flex-layout#1.3.1
├── iron-icons#1.1.3
├── iron-selector#1.5.2
├── paper-header-panel#1.1.6
├── paper-styles#1.1.4
├── paper-toolbar#1.1.4
└── polymer#1.4.0

webcomponentsjs#0.7.22 bower_components/webcomponentsjs

paper-styles#1.1.4 bower_components/paper-styles
├── font-roboto#1.0.1
├── iron-flex-layout#1.3.1
└── polymer#1.4.0

iron-icons#1.1.3 bower_components/iron-icons
├── iron-icon#1.0.8
├── iron-iconset-svg#1.0.9
└── polymer#1.4.0

polymer#1.4.0 bower_components/polymer
└── webcomponentsjs#0.7.22

marked-element#1.1.3 bower_components/marked-element
├── marked#0.3.5
└── polymer#1.4.0

paper-icon-button#1.1.1 bower_components/paper-icon-button
├── iron-icon#1.0.8
├── paper-behaviors#1.0.11
├── paper-styles#1.1.4
└── polymer#1.4.0

prism-element#1.0.4 bower_components/prism-element
├── polymer#1.4.0
└── prism#1.5.0

web-component-tester#4.2.2 bower_components/web-component-tester
├── accessibility-developer-tools#2.10.0
├── async#1.5.2
├── chai#3.5.0
├── lodash#3.10.1
├── mocha#2.5.3
├── sinon-chai#2.8.0
├── sinonjs#1.17.1
├── stacky#1.3.2
└── test-fixture#1.1.1

iron-location#0.8.3 bower_components/iron-location
└── polymer#1.4.0

iron-flex-layout#1.3.1 bower_components/iron-flex-layout
└── polymer#1.4.0

iron-doc-viewer#1.0.14 bower_components/iron-doc-viewer
├── marked-element#1.1.3
├── paper-button#1.0.12
├── paper-styles#1.1.4
├── polymer#1.4.0
└── prism-element#1.0.4

iron-selector#1.5.2 bower_components/iron-selector
└── polymer#1.4.0

paper-header-panel#1.1.6 bower_components/paper-header-panel
├── iron-flex-layout#1.3.1
└── polymer#1.4.0

hydrolysis#1.24.0 bower_components/hydrolysis

iron-ajax#1.2.0 bower_components/iron-ajax
├── polymer#1.4.0
└── promise-polyfill#1.0.0

paper-toolbar#1.1.4 bower_components/paper-toolbar
├── iron-flex-layout#1.3.1
├── paper-styles#1.1.4
└── polymer#1.4.0

font-roboto#1.0.1 bower_components/font-roboto

iron-icon#1.0.8 bower_components/iron-icon
├── iron-flex-layout#1.3.1
├── iron-meta#1.1.1
└── polymer#1.4.0

iron-iconset-svg#1.0.9 bower_components/iron-iconset-svg
├── iron-meta#1.1.1
└── polymer#1.4.0

paper-behaviors#1.0.11 bower_components/paper-behaviors
├── iron-behaviors#1.0.16
├── iron-checked-element-behavior#1.0.4
├── paper-ripple#1.0.5
└── polymer#1.4.0

test-fixture#1.1.1 bower_components/test-fixture

marked#0.3.5 bower_components/marked

prism#1.5.0 bower_components/prism

accessibility-developer-tools#2.10.0 bower_components/accessibility-developer-tools

lodash#3.10.1 bower_components/lodash

mocha#2.5.3 bower_components/mocha

sinon-chai#2.8.0 bower_components/sinon-chai

stacky#1.3.2 bower_components/stacky

sinonjs#1.17.1 bower_components/sinonjs

paper-button#1.0.12 bower_components/paper-button
├── iron-flex-layout#1.3.1
├── paper-behaviors#1.0.11
├── paper-material#1.0.6
└── polymer#1.4.0

promise-polyfill#1.0.0 bower_components/promise-polyfill
└── polymer#1.4.0

iron-checked-element-behavior#1.0.4 bower_components/iron-checked-element-behavior
├── iron-form-element-behavior#1.0.6
├── iron-validatable-behavior#1.1.1
└── polymer#1.4.0

iron-meta#1.1.1 bower_components/iron-meta
└── polymer#1.4.0

chai#3.5.0 bower_components/chai

iron-behaviors#1.0.16 bower_components/iron-behaviors
├── iron-a11y-keys-behavior#1.1.2
└── polymer#1.4.0

paper-material#1.0.6 bower_components/paper-material
├── paper-styles#1.1.4
└── polymer#1.4.0

paper-ripple#1.0.5 bower_components/paper-ripple
├── iron-a11y-keys-behavior#1.1.2
└── polymer#1.4.0

async#1.5.2 bower_components/async

iron-validatable-behavior#1.1.1 bower_components/iron-validatable-behavior
├── iron-meta#1.1.1
└── polymer#1.4.0

iron-form-element-behavior#1.0.6 bower_components/iron-form-element-behavior
└── polymer#1.4.0

iron-a11y-keys-behavior#1.1.2 bower_components/iron-a11y-keys-behavior
└── polymer#1.4.0

Setup Complete!
Check out your new project README for information about what to do next.

[sc-toolbox]$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/test/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator_test.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/web-component-tester/data/index.html_script_2.js
error:   Promise rejection: Error: no resolver found for /src/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator.html
error:   Error: no resolver found for /src/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator.html
    at FileLoader.request (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer.load (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:121:32)
    at Analyzer._getDependencies (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:401:25)
    at Analyzer._parseHTML (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:227:50)
    at Timeout._onTimeout (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
error:   Promise rejection: Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
error:   Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
    at FileLoader.request (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
error:   Promise rejection: Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
error:   Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
    at FileLoader.request (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
error:   Promise rejection: Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
error:   Error: no resolver found for /bower_components/webcomponentsjs/webcomponents-lite.js
    at FileLoader.request (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (/home/davidmaxwaterman/z/polymer-cli/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
[sc-toolbox]$ 
```

Any advice on how to move forward with this issue?

**Comment by davidmaxwaterman** [comment]
aside: I'm curious why `polymer build` is trying to uglify files in /tests.

**Comment by justinfagnani** [comment]
Thanks for the report. This is similar to something I was working on yesterday which I thought was only occurring on Windows.

We shouldn't normally be optimizing files in `test/`, that's either a bug, or you may have a reference from `src/` into `test/`, possibly via an HTML import.

**Comment by davidmaxwaterman** [comment]
FWIW, I haven't changed any of the source files....or any files at all actually...since `polymer init`.

**Comment by kmdupr33** [comment]
I'm having a similar issue.

**Comment by FredKSchott** [comment]
I can reproduce in the shop template.

**Comment by FredKSchott** [comment]
https://github.com/Polymer/polymer-cli/issues/219 actually fixes this for me on Mac. 

I would appreciate if someone running into this problem could check out the branch from #219 and run locally, and confirm that it fixes it for them as well.

**Comment by davidmaxwaterman** [comment]
I'm trying the branch `windows` (I think that's right from #216)...npm install is taking forever :/

**Comment by davidmaxwaterman** [comment]
ok, I still get the issue with the warning about uglifying the tests, and others in bower_components, but the build does actually complete :

```
[sc-toolbox]$ (cd ~/z/polymer-cli/ && git log | head)
commit 363243c1851eabbbdc5ec245fbbcdcdd4c5ea5c0
Author: Justin Fagnani <justinfagnani@google.com>
Date:   Fri May 27 14:29:08 2016 -0700

    add HtmlProject test

commit 10e619cbdd5c58c5eb788be832549364419cdc97
Author: Justin Fagnani <justinfagnani@google.com>
Date:   Thu May 26 16:29:46 2016 -0700
[sc-toolbox]$ ls -i /home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/../lib/node_modules/polymer-cli/bin/polymer.js
11885941 /home/davidmaxwaterman/.nvm/versions/node/v6.2.0/bin/../lib/node_modules/polymer-cli/bin/polymer.js
[sc-toolbox]$ ls -i ~/z/polymer-cli/bin/polymer.js 
11885941 /home/davidmaxwaterman/z/polymer-cli/bin/polymer.js
[sc-toolbox]$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/test/o1-webapps-scientific-calculator/o1-webapps-scientific-calculator_test.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /home/davidmaxwaterman/z/webapps/sc-toolbox/bower_components/web-component-tester/data/index.html_script_2.js
info:    Generating service workers...
info:    Build complete!
[sc-toolbox]$ 
```

**Comment by akc42** [comment]
My most important issue is that I am getting some failures
```
error:   Uncaught exception: TypeError: Cannot read property 'previous' of null
error:   TypeError: Cannot read property 'previous' of null
    at Parser.parseDeclarationOrRuleset (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:192:63)
    at Parser.parseRule (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:80:21)
    at Parser.parseRulelist (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:153:27)
    at Parser.parseDeclarationOrRuleset (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:212:87)
    at Parser.parseRule (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:80:21)
    at Parser.parseRules (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:62:25)
    at Parser.parseStylesheet (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:55:47)
    at Parser.parse (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/shady-css-parser/dist/shady-css/parser.js:51:19)
    at css (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:51:39)
    at dom5.queryAll.forEach.styleNode (/home/alan/.nvm/versions/node/v6.2.0/lib/node_modules/polymer-cli/node_modules/css-slam/index.js:45:36)
```
This is the first, there is a second failure similar but different.  The net result is my build/bundled and build/unbundled src directories are missing files from the back end of the alphabet. 

The file I think it is failing on is not referenced anywhere down any html import chain from either the shell or any fragment, its just sitting there as I slowly move my app over from its previous page.js driven router and with everything imported via  elements.html to the new ppl pattern.


I'm am also getting unable to uglify messages in my bower components,

```
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/platinum-push-messaging/service-worker.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb-find/index.html_script_0.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/compiler.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/core.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/en.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/es5.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/main.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/intl-messageformat/src/utils.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/src/moment.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/amd-named.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/amd.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/default.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/globals.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/locale-header.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/moment/templates/test-header.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb/src/index.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb/src/pouchdb-browser.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb/src/pouchdb.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb-find/bin/es3ify.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/pouchdb-find/bin/test-browser.js
warn:    Unable to uglify file /home/alan/dev/pasv5/app/bower_components/source-map/bench/bench-dom-bindings.js
```

**Comment by reajuria** [comment]
Try adding the polymer.json file, in my setup this resolved the issue. https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build

**Comment by JBClion** [comment]
Have the same issue as @reajuria:

error:   Error: no resolver found for ../bower_components/promise-polyfill/Promise.js

**Comment by oneezy** [comment]
I'm getting the same `'previous' of null` error as @akc42 ... any resolution to this yet guys?

```
$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Uncaught exception: TypeError: Cannot read property 'previous' of null
error:   TypeError: Cannot read property 'previous' of null
    at Parser.parseDeclarationOrRuleset (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:192:63)
    at Parser.parseRule (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRulelist (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:153:27)
    at Parser.parseDeclarationOrRuleset (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:212:87)
    at Parser.parseRule (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:80:21)
    at Parser.parseRules (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:62:25)
    at Parser.parseStylesheet (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:55:47)
    at Parser.parse (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\node_modules\shady-css-parser\dist\shady-css\parser.js:51:19)
    at css (C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\index.js:51:39)
    at C:\Users\Oneeezy\AppData\Roaming\nvm\v4.2.1\node_modules\polymer-cli\node_modules\css-slam\index.js:45:36
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\demo\index.html_script_0.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_0.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_1.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_2.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_3.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\marked-element\test\marked-element.html_script_4.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\web-component-tester\data\index.html_script_0.js
warn:    Unable to uglify file C:\Users\Oneeezy\Desktop\www_\_clients\diesel\wwwSFI\bower_components\web-component-tester\data\index.html_script_2.js

```

**Comment by FredKSchott** [comment]
Fixed in [v0.13.0](https://github.com/Polymer/polymer-cli/releases/tag/v0.13.0)

**Comment by JGSolutions** [comment]
I still get warning about these similar issues above. I am using 0.14.0 version

**Comment by FredKSchott** [comment]
@JGSolutions can you create a new issue with steps to reproduce so that we can take a look in the latest version? Thanks!

**Comment by JGSolutions** [comment]
I figured it out and the reason why was I had ES6 syntax arrow functions.

**Comment by FredKSchott** [comment]
nice! We use uglify internally in polymer-cli, which doesn't support much ES6 syntax. If this is something you need, consider implementing your own build pipeline with [polymer-build](https://github.com/Polymer/polymer-build)

**Comment by JGSolutions** [comment]
Yes polymer-build is something I will look into eventually. Thanks

**Comment by ziszo** [comment]
I'm currently facing an issue in **_build_**ing:

**no such file or directory, ... promise-polyfill/promise-polyfill.html**

which is not really in my bower_components/promise-polyfill directory.

Please help @FredKSchott. Thanks.

**Comment by justinfagnani** [comment]
@ziszo that warning sounds real. Some file is importing promise-polyfill.html, but it didn't get installed in bower_components. Make sure you ran `bower i`. Did the warning include context about which file referenced it?

**Comment by ziszo** [comment]
@justinfagnani it didn't showed what files referenced it, but Sublime Text 2 (search result for all files in my app directory) shows serveral elements that are importing the file. app-storage-behavior.html is one of those files. Many other files include several iron elements.

**Comment by ziszo** [comment]
I've run **bower i** and got the same errors.

**Comment by justinfagnani** [comment]
Can you verify that `bower_components/promise-polyfill/promise-polyfill.html` is missing (or not)?
app-storage includes a promise-polyfill dependency: https://github.com/PolymerElements/app-storage/blob/master/bower.json#L19 so it should be installed.

**Comment by ziszo** [comment]
@justinfagnani Yes.. bower_components/promise-polyfill/promise-polyfill.html is mising.
There's nothing wrong with app-storage or any other elements I think. It's the promise-polyfill that has a problem.

**Comment by justinfagnani** [comment]
Ok, I'm confused. If you ran bower install, you should have `bower_components/promise-polyfill/promise-polyfill.html`.

**Comment by ziszo** [comment]
@justinfagnani The promise-polymer folder is present in bower_components. It's just that there's no promise-polyfill.html even if I already ran bower i.
