### ISSUE TITLE
External domains in script tags breaks build

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-cli#261]
As reported by @edoardo849 in #222 

```html
<script type="text/javascript" src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
```

Causes an error due to no resolver being found.

@garlicnation is the standard practice to add a resolver that ignores these URLs?

**Comment by MrTeutonic** [comment]
Sounds related and might help to find a solution: I use App drawer template and use firebase-app.html and polymerfire.html.
Have done quite some mondification to the code including changes from my-app to myname-app and so on.
Now, during first time polymer build I get an error:
```
Promise rejection: Error: no resolver found for https://www.gstatic.com/firebasejs/live/3.0/firebase.js
Error: no resolver found for https://www.gstatic.com/firebasejs/live/3.0/firebase.js

```

**Comment by admwx7** [comment]
Is there a work-around for this in the meantime?

Also curious to hear what the preferred approach for handling this would be, might look into adding support if I get some free time.

**Comment by edvail** [comment]
I can't use google-chart due to this issue:
no resolver found for https://www.gstatic.com/charts/loader.js

Is there any workaround to still build somehow project?

**Comment by houston88** [comment]
I get this error as well when trying to use google-chart, and then build fails.

**Comment by garlicnation** [comment]
@justinfagnani The NoopResolver is for this situation.

**Comment by FredKSchott** [comment]
I just submitted a fix to this to polymer-build, which means this will get
the fix as well.

**Comment by FredKSchott** [comment]
Fix in PR here: https://github.com/Polymer/polymer-build/pull/16

**Comment by FredKSchott** [comment]
Fixed in polymer-build v0.3.2 & polymer-cli v0.13.0!

**Comment by FredKSchott** [comment]
@garlicnation is right, this only fixed half of the problem. We need to handle this in Hydrolysis as well. Working on a fix now...

**Comment by 43081j** [comment]
@FredKSchott this appears to still happen in `polymer lint`, is it due to the same issue?

**Comment by FredKSchott** [comment]
@43081j no you're right, it's still happening in current polymer-cli (v0.13.0) but will be fixed in v0.14.0 (releasing today). Thanks for confirming!

**Comment by FredKSchott** [comment]
Released! If you were running into this bug please update the CLI and re-try. Open another issue if you're still having trouble.

Thanks!

**Comment by zreptil** [comment]
Is there meanwhile a working fix for it? I run into the same issue. Google Charts is not working correctly because of this. Can i change anything in my polymer app to get it working again?

**Comment by FredKSchott** [comment]
@zreptil you're still running into this? This was fixed in the latest version of the CLI. Have you tried updating/reinstalling?

If you're still seeing a bug, please open a new issue https://github.com/Polymer/polymer-cli/issues/new

**Comment by zreptil** [comment]
@FredKSchott 

i installed polymer-cli again and run again in issues. but they weren't related to google-charts. now it seems to work correct. in my code i had to change the calls of drawChart () to redraw() for google-charts to work again. Maybe there was an update that i missed recently.

So this issue is fixed for me. Thanks for the info :)

**Comment by FredKSchott** [comment]
Woo! Glad you were able to get it working

**Comment by jpincas** [comment]
Just posted on the PR, but reposting here:

`<link rel="import" href="http://localhost:3000/admin-panel/polymer-imports.html">`

and it is causing a build error.

Looking through the code a bit more closely I can see that ignoring external dependencies only applies to script and style dependencies. Is there a particular reason for this? I am importing a dynamically rendered html file from an external server which contains a lot of setup information as behaviors. It works perfectly with 'polymer serve' and seems like a good architecture. Is it unwise for some reason?
