### ISSUE TITLE
polymer build error parsing script 'x' at NaN:NaN undefined

### ISSUE THREAD

**Issue by elonmallin** [Polymer/polymer-cli#512]
### Description
If you do `polymer build` and you have this syntax error:
```
properties: {
  someProp: {
    type: Boolean,
    type: false, // Should be 'value' not 'type'!
  }
}
```
You will be met with and error as shown below.

Filed this issue in the wrong place first [Polymer/polymer-analyzer#408](https://github.com/Polymer/polymer-analyzer/issues/408#issuecomment-267038767) and got a comment that it is because of `hydrolysis`.

### Versions & Environment
- Polymer CLI: 0.17.0
- node: v4.3.1
- Operating System: Windows 10 Pro

#### Steps to Reproduce
Run `polymer build` and have a component with the script error like in the description.

#### Expected Results
No error and finished build.

#### Actual Results
```
error:   Promise rejection: Error: Error parsing script in x.html at NaN:NaN
undefined
error:   Error: Error parsing script in x.html at NaN:NaN
undefined
    at Analyzer._processScript (...\node_modules\hydrolysis\lib\analyzer.js:331:36)
    at ...\node_modules\hydrolysis\lib\analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (...\node_modules\hydrolysis\lib\analyzer.js:300:21)
    at Analyzer._parseHTML (...\node_modules\hydrolysis\lib\analyzer.js:161:39)
    at null._onTimeout (...\node_modules\hydrolysis\lib\analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by FredKSchott** [comment]
@elonmallin ugh yea, that's our old analyzer. This should be fixed on `master`, Can you try `npm install -g polymer-build@next` to get a prerelease version of the CLI and confirm that this is fixed?

**Comment by filipproch** [comment]
I am seeing this error too
@FredKSchott I have "polymer-build": "^0.6.0-alpha.1" and still getting
```
 Error: Error parsing script in .../src/elements/x.html at NaN:NaN
TypeError: Cannot read property 'forEach' of undefined
    at Object.enterMethodDefinition (.../node_modules/hydrolysis/lib/ast-utils/element-finder.js:88:38)
    at applyVisitors (.../node_modules/hydrolysis/lib/ast-utils/js-parse.js:31:51)
    at Controller.enter (.../node_modules/hydrolysis/lib/ast-utils/js-parse.js:54:20)
    at Controller.__execute (.../node_modules/hydrolysis/node_modules/estraverse/estraverse.js:395:31)
    at Controller.traverse (.../node_modules/hydrolysis/node_modules/estraverse/estraverse.js:493:28)
    at Object.traverse (.../node_modules/hydrolysis/node_modules/estraverse/estraverse.js:705:27)
    at Object.jsParse (.../node_modules/hydrolysis/lib/ast-utils/js-parse.js:75:16)
    at Analyzer._processScript (.../node_modules/hydrolysis/lib/analyzer.js:318:43)
    at .../node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScript (.../node_modules/hydrolysis/lib/analyzer.js:331:36)
    at .../node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (.../node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (.../node_modules/hydrolysis/lib/analyzer.js:161:39)
    at Timeout._onTimeout (.../node_modules/hydrolysis/lib/analyzer.js:125:39)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

and my build sequence looks like this

```
let sourcesStream = project.sources()
    .pipe(project.splitHtml())
    .pipe(gulpif('*.js', babel({ presets: [ 'es2015' ] })))
    .pipe(gulpif('*.js', uglify({ mangle: false })))
    .pipe(gulpif('*.html', htmlmin({
      collapseWhitespace: true,
      caseSensitive: true,
      minifyCSS: true
    })))
    .pipe(gulpif('*.{png,gif,jpg,svg}', imagemin({ progressive: true, interlaced: true })))
    .pipe(project.rejoinHtml())

  // process dependencies
  let dependenciesStream = project.dependencies()
    .pipe(project.splitHtml())
    .pipe(project.rejoinHtml())

  mergeStream(sourcesStream, dependenciesStream)
    .pipe(project.bundler)
    .pipe(gulp.dest('build/'))
```

**Comment by elonmallin** [comment]
Yea that could possibly be working. I got a bunch of Unable to resolve behaviors errors instead like:
```
error:   In bower_components/paper-input/paper-input.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronFormElementBehavior`. Did you import it? Is it annotat
ed with @polymerBehavior?
```
I got 5 of these similar errors so I'm not sure if the build stops before it can get to the error I had though because I assume it's not ignored now and it doesn't show up in the output. I may have some version outdated paper-input so that's probably why I'm seeing this.

**Comment by elonmallin** [comment]
@filipproch you have a really old version it seems and the error was still in my version `0.17.0` so makes sense for yours `0.6.0-alpha.1` to have it too. And your output mentions `hydrolysis` which seems like it should be something they aren't using anymore in the supposedly working version which is 0.18.something.

**Comment by web-padawan** [comment]
> I have "polymer-build": "^0.6.0-alpha.1" and still getting
I guess this is happening via `hydrolysis` usage by `vulcanize`.

>I got a bunch of Unable to resolve behaviors errors
There is a reason: https://github.com/Polymer/polymer-build/issues/85

**Comment by FredKSchott** [comment]
@filipproch can you try removing the bundling step from your build? If the error goes away, we can confirm it's originating in the bundler.

One thing that always helps me debug these build issues is to go through your project and clear each file, periodically re-running build to see if the issue disappears (hopefully leading you to the issue in your code). Our newer tools are much better at reporting these types of application errors, but some of our old tools still fail internally instead.

**Comment by filipproch** [comment]
@FredKSchott yep, removing the bundler part removes the issue and the build succeeds

however, I had to modify __polymer-element-scanner.js__ file (adding undefined check) in polymer-analyzer first as otherwise I was getting this error :
```
TypeError: Cannot read property 'forEach' of undefined
    at ElementVisitor.enterMethodDefinition (.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/polymer/polymer-element-scanner.js:109:34)
    at applyScanners (.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/javascript/javascript-document.js:42:57)
    at Controller.enter (.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/javascript/javascript-document.js:92:17)
    at Controller.__execute (.../node_modules/polymer-build/node_modules/estraverse/estraverse.js:395:31)
    at Controller.traverse (.../node_modules/polymer-build/node_modules/estraverse/estraverse.js:493:28)
    at Object.traverse (.../node_modules/polymer-build/node_modules/estraverse/estraverse.js:705:27)
    at JavaScriptDocument.visit (.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/javascript/javascript-document.js:90:22)
    at runVisitors (.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/scanning/scan.js:55:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

It occurs right after this line
```
debug:   new dependency found, pushing into dependency stream... .../bower_components/polymer/polymer.html
```

I first commented out all files in my project (except for shell file, which has only one dependency, polymer.html, everything else is commented out). If I edit the file mentioned above, then those errors disappear. And without the bundler part the build succeeds

**Comment by FredKSchott** [comment]
@filipproch mind filing a new issue and copy and pasting the relevant bits from this conversation into it? I want to separate this from @elonmallin's issue with the syntax error.

Can you include your `.../src/elements/x.html` file in a gist as well? I think there might be a hard-to-spot error in how that file is written that our analyzer isn't able to handle.

**Comment by filipproch** [comment]
@FredKSchott sure, should I file it in the analyzer repo or here?

**Comment by FredKSchott** [comment]
@filipproch analyzer repo is probably the most appropriate for the error you're seeing in polymer-analyzer (`.../node_modules/polymer-build/node_modules/polymer-analyzer/lib/polymer/polymer-element-scanner.js:109:34`), but please mention that you're using it with build.

**Comment by FredKSchott** [comment]
@elonmallin just to be clear, our build can't analyze your code when your javascript has a syntax error in it. So for your original error, it is expected that build will fail with a helpful error message explaining the syntax error. 

We'll keep this issue to track the bad error message (`NaN:NaN`) which we can hopefully fix at the same time as @filipproch's bug in polymer-analyzer.

**Comment by elonmallin** [comment]
Yep, that's what I meant. Updated the expected text.

**Comment by FredKSchott** [comment]
@elonmallin as I mentioned in https://github.com/Polymer/polymer-analyzer/issues/408, this is an issue in our old analyzer. Our current plan is to get our latest tooling out to the public asap, which means we probably won't have time to go back fix this in the old analyzer. 

I'd recommend hunting down those "unable to resolve behavior" errors that build is giving you on the `next` version of the CLI, those might even be the same error that hydrolysis is failing on.
